-- Rodada 2 / Bloco A.4 — Novos campos cadastrais em usuarios
-- Executar antes de publicar o form atualizado (app/usuarios.php).

ALTER TABLE usuarios
    ADD COLUMN USU_CPF_CNPJ    VARCHAR(20)  NULL AFTER USU_CARGO,
    ADD COLUMN USU_TELEFONE    VARCHAR(20)  NULL AFTER USU_CPF_CNPJ,
    ADD COLUMN USU_CEP         VARCHAR(9)   NULL AFTER USU_TELEFONE,
    ADD COLUMN USU_ENDERECO    VARCHAR(200) NULL AFTER USU_CEP,
    ADD COLUMN USU_NUMERO      VARCHAR(20)  NULL AFTER USU_ENDERECO,
    ADD COLUMN USU_COMPLEMENTO VARCHAR(100) NULL AFTER USU_NUMERO,
    ADD COLUMN USU_BAIRRO      VARCHAR(100) NULL AFTER USU_COMPLEMENTO,
    ADD COLUMN USU_CIDADE      VARCHAR(100) NULL AFTER USU_BAIRRO,
    ADD COLUMN USU_UF          VARCHAR(2)   NULL AFTER USU_CIDADE;
